### ISSUE TITLE
Dynamically sending message, doesn't trigger retry and DLQ

### ISSUE THREAD

**Issue by legendjaks** [spring-cloud/spring-cloud-stream#1757]
Using Spring Boot 2.1.5.RELEASE and Cloud Greenwich.SR1. 

I have tried the sample from [SourceWithDynamicDestination](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/source-samples/dynamic-destination-source/src/main/java/demo/SourceWithDynamicDestination.java). It is sending the message to the relevant queue, but on failure expected retry & moving to DLQ is not happening.

Here is the sample project which demonstrates the issue [spring-cloud-stream-kafka-dlq](https://github.com/legendjaks/sc-kafka-dlq/tree/master)

Publish message `curl -X POST 'http://localhost:8080/producer/delta' -H 'Content-Type: application/json' -d '{"sku":"abc","quantity":0}'`. See that 3 retries worked and message is pushed to DLQ after 3 retries.

Test dynamic messaging `curl -X POST 'http://localhost:8080/producer/dynamic' -H 'Content-Type: text/plain' -d '{"channel":"processPFSOrders", "sku":"xyz","quantity":0}'`. Note that it failed at first time itself. The retries are not happening, also message was not sent to DLQ

Please let me know if any config is missing.

**Comment by olegz** [comment]
I am not sure why you're mentioning `Boot 2.1.5.RELEASE and Cloud Greenwich.S` and not the actual version of spring-cloud-stream you're using. We are currently in Germantown which is 2.2.0. There were issues with DLQ. hey have been addressed so please see if you can upgrade and let us know.

**Comment by legendjaks** [comment]
I was using Sprint Initializer and not aware of adding cloud-stream BOM. Now I have added `Spring Cloud Stream Germantown.RELEASE` and `Spring Cloud Function Context 2.1.1.RELEASE`. Still, the problem persists. The message was received by the StreamListener, but while throwing an exception, it is not retrying and not sending it to DLQ. Any headers have to be added while posting to the topic for retry & DLQ? Updated the code in the repo [spring-cloud-stream-kafka-dlq](https://github.com/legendjaks/sc-kafka-dlq/tree/master)

**Comment by legendjaks** [comment]
Sorry. It is my mistake. Instead of posting the message to `producer`, I have called `consumer`. Trying to post to the queue `postInventoryChange` worked with retry & DLQ.
