### ISSUE TITLE
Massive Logging when using StreamBridge

### ISSUE THREAD

**Issue by dbruegger** [spring-cloud/spring-cloud-stream#2034]
**Description**

We use StreamBridge to send messages triggered by a foreign source. The messages are sent successfully but it fills our log with logging messages such like this:

```
2020-10-15 08:46:00.905  INFO [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'streamBridge' with acceptedOutputTypes: [application/json]
```

The log message is logged each time the StreamBridge.send() method is called.

Our binding configuration looks like this:

```
spring:
  cloud:
    stream:
      default:
        group: ${application.name}
        consumer.autoStartup: false
        producer.autoStartup: false
      source: locationUpdatedEvent;pathUpdatedEvent
      bindings:
        locationUpdatedEvent-out-0:
          destination: x/y/z/movement-tracking/v1/LocationUpdatedEvent
        pathUpdatedEvent-out-0:
          destination: x/y/z/movement-tracking/v1/PathUpdatedEvent
```

Our application code looks like this:

```
@Service
public class MovementTrackingPublisher {

    private final StreamBridge streamBridge;

    @Autowired
    public MovementTrackingPublisher(StreamBridge streamBridge) {
        this.streamBridge = requireNonNull(streamBridge);
    }

    public void publishLocationUpdatedEvent(LocationUpdatedEvent event) {
        streamBridge.send("locationUpdatedEvent-out-0", MessageBuilder.withPayload(event).build());
    }

    public void publishPathUpdatedEvent(PathUpdatedEvent event) {
        streamBridge.send("pathUpdatedEvent-out-0", MessageBuilder.withPayload(event).build());
    }

}
```

**Version of the framework**

- Spring Boot 2.2.6.RELEASE
- Spring Cloud Hoxton.SR8
- Spring Cloud Stream 3.0.6.RELEASE (an update to 3.0.8.RELEASE did not solve the problem)
- Spring Cloud Stream Binder for Solace PubSub+ 2.1.1

**Expected behavior**

The function lookup is either logged with DEBUG level or logged only once with INFO level.

**Comment by olegz** [comment]
It's been addressed on the function side, but i';ll keep this issue open until the fix is merged

**Comment by olegz** [comment]
@dbruegger the changes to function master have been pushed (the latest commits there) and aside form simplifying logging the actual lookups have been streamlined as well so there is not that many of them. Please give it a shot and let us know

**Comment by dbruegger** [comment]
Is there a Snapshot Repository?

**Comment by olegz** [comment]
Yes, you can use
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-dependencies</artifactId>
	<version>3.1.0-SNAPSHOT</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>
```

**Comment by dbruegger** [comment]
Thank you!

I retested with the newest snapshot versions. The log message
```c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'streamBridge' with acceptedOutputTypes: [application/json]```
does not appear anymore.

I still see some log messages which I can't explain. The following warning occurs 5 times during the Spring initialization phase:
2020-10-26 14:31:35.737  WARN [shas-movement-tracking,,,] 13436 --- [           main] o.s.c.s.b.AbstractMessageChannelBinder$1 : It seems that this message occurs only in our integration tests using the spring-cloud-stream test binder.

**Comment by dbruegger** [comment]
I retested with the milestone version which was released yesterday (spring-cloud-stream:3.1.0-M4).

Whereas the before mentioned log messages do not appear anymore, a new log message is logged on each message which is handled by Spring Cloud Stream:

```
2020-11-18 13:58:28.067  INFO [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Executing around advise(s)
```

I would not expect such logging messages to be logged with INFO level on each message handled.

**Comment by dbruegger** [comment]
Opened a more specific issue (#2075) for the remaining problem.

**Comment by dbruegger** [comment]
With Spring Cloud Stream 3.2.3 there is again an INFO log message on every call to `StreamBridge.send()`:

```
2022-05-05 12:05:54.595  INFO [pool-1-thread-1] o.s.c.s.binder.DefaultBinderFactory      : Retrieving cached binder: solace 
```

I would still expect that such messaged are logged with DEBUG level or only once with INFO level.

**Comment by dbruegger** [comment]
The issue still exists with Spring Cloud Stream 3.2.4.

**Comment by GreenRover** [comment]
@olegz What do you guess, can we get the log of the streamBridge be less verbose on level INFO?

**Comment by olegz** [comment]
we're fixing it and it is not related to stream bridge, rather a general issue
