### ISSUE TITLE
Function not picked up as Binding if spring-cloud-task-stream and actuator are present

### ISSUE THREAD

**Issue by stoetti** [spring-cloud/spring-cloud-stream#2092]
I have a Spring Boot service that uses Spring Cloud Dataflow for orchestrating tasks and streams. To keep the internal state of the tasks updated I wanted to use Spring Cloud Stream for consuming the message provided by Spring Cloud Task. In order to have the right Pojos for deserializing the payload I needed to include a dependency on spring-cloud-task-stream.
As soon as this dependency was part of my project the Consumer-Beans have not been picked up by Spring Cloud Stream as functions and no bindings have been created.

To figure out the real cause I put toghether a minimum sample project and wrote two unit tests showing the expected and the erroneous behavior (https://github.com/stoetti/task-stream-function).
As far as I analyzed removing either actuator or task-stream leads to the expected behavior, so for now I just excluded the TaskEventAutoConfiguration as I don't need that, just need the classes of the library.

I am using Spring Boot 2.4.1 and Spring Cloud 2020.0.0

**Comment by olegz** [comment]
You have two consumers effectively creating a conflict where we can not determine your intentions. 

You should see the following statement in logs if you enable debug `logging.level.org.springframework.cloud.function=debug`

```
2021-01-26 08:03:12.673 DEBUG 10649 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Can't determine default function name
```

By default we're only going to auto-bind a single function. If your intention is to bind several you should explicitly state this via `spring.cloud.function.definition` property delimiting function definitions by `;` 
For example, `spring.cloud.function.definition=messageConsumer;anotherMessageConsumer`.

I'll make logging for this a bit more explicit and INFO.

**Comment by olegz** [comment]
Resolving it with https://github.com/spring-cloud/spring-cloud-function/commit/0e6260942b15020d0413bff0e46ea7f1d7f1c073

**Comment by stoetti** [comment]
@olegz 
actually I have this configuration in the external configuration https://github.com/stoetti/task-stream-function/blob/master/src/test/resources/application.properties maybe should have put that part of the configuration into the unit test as well, I just committed this update.

Please reopen as the issue is still present and in my opinion does not have something to do with misconfiguration.

**Comment by olegz** [comment]
Actually it contains non of what I discussed - https://github.com/stoetti/task-stream-function/blob/master/src/test/resources/application.properties
What am I missing?

**Comment by stoetti** [comment]
Sorry for the misunderstanding.
Based on your first reply I updated the unit test and moved the function definition to the @SpringBootTest-annotation to make it obvious which function shall be loaded.

**Comment by olegz** [comment]
Ok, I still don't understand what do you mean when you say `Function not picked up as Binding`. 
As far as I see everything works as expected and function(s) is bound properly as it is seen in `BindingService` bean

What are you attempting to test here?:
```
assertThat(context.containsBeanDefinition("messageConsumer-in-0")).isTrue();
```
Bindings are not registered as a bean


Anyway, this doesn't seem like an issue, rather miss-understanding  and we do not use this issue tracker for general purpose Q&A and support questions. Please use our [dedicated Stack Overflow](https://stackoverflow.com/questions/tagged/spring-cloud-stream) channel for that.
