### ISSUE TITLE
Nullpointer exception when return null message in functional streaming

### ISSUE THREAD

**Issue by matus753** [spring-cloud/spring-cloud-stream#2107]
In short when i return null using functional programming model instead of filtering message i get `java.lang.NullPointerException: null`

This is what we were using until now: 
```java
@EnableBinding(Processor.class)
public class ClassName {

    @StreamListener(Sink.INPUT)
    @SendTo(OUTPUT)
    public Message<OutputClass> process(@Payload InputClass input) {
        if (isMessageWrong) {
            // this the way we were filtering messages
            log.info(FILTERED_UNSUPPORTED_MESSAGE, key);
            return null;
        }
        return MessageBuilder
                    .withPayload(buildPayload(input))
                    .setHeader(Constants.MESSAGE_KEY_OUTGOING, key)
                    .build();
}
```

After upgrade to spring boot 2.4.2 and upgrade spring cloud stream to 3.1.0 is this aproach depreacted:
`* @deprecated as of 3.1 in favor of functional programming model`

so we rework code to this, using functional programming model:
```java
@Component
public class ClassName implements Function<Message<InputClass>, Message<OutputClass>> {

    @Override
    public Message<OutputClass> apply(@Payload InputClass input) {
        if (isMessageWrong) {
            // this the way we are trying to filter messages
            log.info(FILTERED_UNSUPPORTED_MESSAGE, key);
            return null;
        }
        return MessageBuilder
                    .withPayload(buildPayload(input))
                    .setHeader(Constants.MESSAGE_KEY_OUTGOING, key)
                    .build();
}
```

using this code, when i filter any wrong message and return null i've got this stacktrace:
```
Caused by: java.lang.NullPointerException: null
	at org.springframework.messaging.core.GenericMessagingTemplate.sendTimeout(GenericMessagingTemplate.java:252) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:585) ~[spring-cloud-stream-3.1.0.jar:3.1.0]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:571) ~[spring-cloud-stream-3.1.0.jar:3.1.0]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.4.3.jar:5.4.3]
```

the whole problem in my opinion is starting in `org.springframework.cloud.stream.function.FunctionConfiguration.FunctionToDestinationBinder#createFunctionHandler`
```java
@Override
public void handleMessageInternal(Message<?> message) throws MessagingException {
	Object result = functionInvocationWrapper.apply((Message<byte[]>) message);
	if (result instanceof Iterable) {
		for (Object resultElement : (Iterable<?>) result) {
			this.doSendMessage(resultElement, message);
		}
	}
	else if (ObjectUtils.isArray(result) && !(result instanceof byte[])) {
		for (int i = 0; i < ((Object[]) result).length; i++) {
			this.doSendMessage(((Object[]) result)[i], message);
		}
	}
	else {
		this.doSendMessage(result, message);
	}
}
```
Why there is not any null check? Is there any prediction that users should not return null from thier apply methods? If yes, how am i supposed to skip wrong message?

**Comment by olegz** [comment]
Thanks for reporting this. Will definitely address in the next release and we'll back-port it as well. Meanwhile you can still use the old approach for now.

**Comment by matus753** [comment]
Hi @olegz,
I noticed that you closed this issue with this explanation https://github.com/spring-cloud/spring-cloud-stream/issues/2108#issuecomment-775286862 

So i checked the class SourcePollingChannelAdapter. After litle searching i found that "if" you are describing in your comment which was in the class which SourcePollingChannelAdapter is extending: `org.springframework.integration.endpoint.AbstractPollingEndpoint#doPoll`

Anyway, I controll full stack trace and message never end up here. I checked it in debug mode too.

I am sending full stack trace of my error, please do not hesitate ask me any question if this will not be helpfull 
```
2021-02-09T10:27:16,866Z | [KafkaConsumerDestination{consumerDestinationName='****', partitions=1, dlqName='null'}.container-0-C-1] INFO  o.a.k.clients.consumer.KafkaConsumer - [Consumer clientId=consumer-****-2, groupId=****] Seeking to offset 131679 for partition ****-0
2021-02-09T10:27:16,867Z | [KafkaConsumerDestination{consumerDestinationName='****', partitions=1, dlqName='null'}.container-0-C-1] ERROR o.s.k.l.KafkaMessageListenerContainer$ListenerConsumer - Error handler threw an exception
org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@733caf28]; nested exception is java.lang.NullPointerException, failedMessage=GenericMessage [*]
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:157) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:113) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:2098) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1997) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1924) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1812) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1531) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1178) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1075) ~[spring-kafka-2.6.5.jar:2.6.5]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@733caf28]; nested exception is java.lang.NullPointerException, failedMessage=GenericMessage [payload=byte[707], headers={deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=****, kafka_receivedTopic=****, target-protocol=kafka, skip-input-type-conversion=false, kafka_offset=131679, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@2f90272c, id=55b3dded-65c9-fc4e-674c-9d5b4121f3da, kafka_receivedPartitionId=0, contentType=application/vnd.transaction.v4+avro, kafka_receivedTimestamp=1607516944366, kafka_groupId=****, timestamp=1612866436865}]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2113) ~[spring-kafka-2.6.5.jar:2.6.5]
	... 10 common frames omitted
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@733caf28]; nested exception is java.lang.NullPointerException
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208) ~[spring-integration-core-5.4.3.jar:5.4.3]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:396) ~[spring-integration-kafka-5.4.3.jar:5.4.3]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:78) ~[spring-integration-kafka-5.4.3.jar:5.4.3]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:455) ~[spring-integration-kafka-5.4.3.jar:5.4.3]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:429) ~[spring-integration-kafka-5.4.3.jar:5.4.3]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.1.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:255) ~[spring-retry-1.3.1.jar:na]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2065) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2047) ~[spring-kafka-2.6.5.jar:2.6.5]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1984) ~[spring-kafka-2.6.5.jar:2.6.5]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.messaging.core.GenericMessagingTemplate.sendTimeout(GenericMessagingTemplate.java:252) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:585) ~[spring-cloud-stream-3.1.0.jar:3.1.0]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:571) ~[spring-cloud-stream-3.1.0.jar:3.1.0]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.4.3.jar:5.4.3]
	... 31 common frames omitted
```

**Comment by Chr3is** [comment]
I'm facing the same NPE when returning null values via the functional approach.

Working imperative approach:

```
@StreamListener(IncomingEvent.MyEvent)
@SendTo(OutgoingEvent.MyEvent)
@Nullable
public MyOutgoingEvent handleEvent(
        @Payload MyIncomingEvent event,
        @Header(RECEIVED_TOPIC) String topic,
        @Header(RECEIVED_PARTITION_ID) int partitionId,
        @Header(CONSUMER) Consumer<?, ?> consumer,
        @Header(ACKNOWLEDGMENT) Acknowledgment acknowledgment) {
    return super.handleEvent(event, topic, partitionId, consumer, acknowledgment);
}
```
Not working functional approach:

```
@Nullable
public R handleIncomingMessage(Message<T> eventMessage) {
    T event = eventMessage.getPayload();
    String topic = eventMessage.getHeaders().get(RECEIVED_TOPIC, String.class);
    Integer partitionId = eventMessage.getHeaders().get(RECEIVED_PARTITION_ID, Integer.class);
    Consumer<?, ?> consumer = eventMessage.getHeaders().get(CONSUMER, Consumer.class);
    Acknowledgment acknowledgment = eventMessage.getHeaders().get(ACKNOWLEDGMENT, Acknowledgment.class);
    return handleEvent(event, topic, partitionId, consumer, acknowledgment);
}

@Bean
Function<Message<MyIncomingEvent>, MyOutgoingEvent> myProcessor(...);
    return new MyStreamHandler(...)::handleIncomingMessage;
}


2021-02-09 12:46:13.476 ERROR 1376 --- [container-0-C-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@7cc9c4c7]; nested exception is java.lang.NullPointerException, failedMessage=GenericMessage [payload={...}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:396)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:78)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:455)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:429)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2065)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2047)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1984)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1924)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1812)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1531)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1178)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1075)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.springframework.messaging.core.GenericMessagingTemplate.sendTimeout(GenericMessagingTemplate.java:252)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:585)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:571)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 27 more
```
Used versions:

```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ malwaredetection-web ---
...
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-kafka:jar:3.1.0:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:3.1.0:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-binder-kafka-core:jar:3.1.0:compile
[INFO] |     |  \- org.springframework.integration:spring-integration-kafka:jar:5.4.3:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream:jar:3.1.0:compile
[INFO] |     +- org.apache.kafka:kafka-clients:jar:2.6.0:compile
[INFO] |     |  +- com.github.luben:zstd-jni:jar:1.4.4-7:compile
[INFO] |     |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |     |  \- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO] |     \- org.springframework.kafka:spring-kafka:jar:2.6.5:compile
[INFO] +- org.springframework.cloud:spring-cloud-schema-registry-client:jar:1.1.0:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.3.3:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO] |  \- org.apache.avro:avro:jar:1.9.2:compile
[INFO] +- io.confluent:kafka-streams-avro-serde:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-avro-serializer:jar:6.0.1:compile
[INFO] |  |  \- io.confluent:kafka-schema-serializer:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-schema-registry-client:jar:6.0.1:compile
[INFO] |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |  \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO] |  \- io.confluent:common-utils:jar:6.0.1:compile
...
```

**Comment by olegz** [comment]
@Chr3is I am testing it with the local master, so perhaps it was fixed as part of some other work. Can you please try it with snapshots as I can not reproduce it

**Comment by olegz** [comment]
Also, SourcePolligChannelAdapter is only used for Supplier. Functions are event driven. 

Anyway, i'll look again and wil make sure there is a test that validates it

**Comment by Chr3is** [comment]
@olegz I've included the latest SNAPSHOT (3.1.1-SNAPSHOT) dependency from https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-stream-dependencies/

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream-dependencies</artifactId>
    <version>3.1.1-SNAPSHOT</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

```
which results in following tree:
```
...
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-kafka:jar:3.1.1-SNAPSHOT:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:3.1.1-SNAPSHOT:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-binder-kafka-core:jar:3.1.1-SNAPSHOT:compile
[INFO] |     |  \- org.springframework.integration:spring-integration-kafka:jar:5.4.3:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream:jar:3.1.1-SNAPSHOT:compile
[INFO] |     +- org.apache.kafka:kafka-clients:jar:2.6.0:compile
[INFO] |     |  +- com.github.luben:zstd-jni:jar:1.4.4-7:compile
[INFO] |     |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |     |  \- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO] |     \- org.springframework.kafka:spring-kafka:jar:2.6.5:compile
[INFO] +- org.springframework.cloud:spring-cloud-schema-registry-client:jar:1.1.1-SNAPSHOT:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.3.3:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO] |  \- org.apache.avro:avro:jar:1.9.2:compile
[INFO] +- io.confluent:kafka-streams-avro-serde:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-avro-serializer:jar:6.0.1:compile
[INFO] |  |  \- io.confluent:kafka-schema-serializer:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-schema-registry-client:jar:6.0.1:compile
[INFO] |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |  \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO] |  \- io.confluent:common-utils:jar:6.0.1:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream:test-jar:test-binder:3.1.1-SNAPSHOT:test
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:5.4.3:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.4.2:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:5.4.3:compile
[INFO] |  +- org.springframework.retry:spring-retry:jar:1.3.1:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-function-context:jar:3.1.0:compile
[INFO] |     +- net.jodah:typetools:jar:0.6.2:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-function-core:jar:3.1.0:compile
...
```
but the NPE is still persistent. Is there any newer snapshot build version and if yes where can I find it?

**Comment by olegz** [comment]
Latest snapshot is 3.1.2-SNAPSHOT

**Comment by Chr3is** [comment]
@olegz I do not see any 3.1.2-SNAPSHOT in the snapshot repository (see provided link). Or do I look into the wrong repository section?

**Comment by olegz** [comment]
Perhaps an issue with snapshot publishing, let me look into that, You can of course build it yourself as well. You can `-DskipTests` to make it quicker

**Comment by Chr3is** [comment]
I've built spring-cloud-stream locally and included it in my project:

```
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-kafka:jar:3.1.0:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:3.1.0:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-binder-kafka-core:jar:3.1.0:compile
[INFO] |     |  \- org.springframework.integration:spring-integration-kafka:jar:5.4.3:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream:jar:3.1.2-SNAPSHOT:compile
[INFO] |     +- org.apache.kafka:kafka-clients:jar:2.6.0:compile
[INFO] |     |  +- com.github.luben:zstd-jni:jar:1.4.4-7:compile
[INFO] |     |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |     |  \- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO] |     \- org.springframework.kafka:spring-kafka:jar:2.6.5:compile
[INFO] +- org.springframework.cloud:spring-cloud-schema-registry-client:jar:1.1.0:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.3.3:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO] |  \- org.apache.avro:avro:jar:1.9.2:compile
[INFO] +- io.confluent:kafka-streams-avro-serde:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-avro-serializer:jar:6.0.1:compile
[INFO] |  |  \- io.confluent:kafka-schema-serializer:jar:6.0.1:compile
[INFO] |  +- io.confluent:kafka-schema-registry-client:jar:6.0.1:compile
[INFO] |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |  \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO] |  \- io.confluent:common-utils:jar:6.0.1:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream:test-jar:test-binder:3.1.0:test
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:5.4.3:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.4.2:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:5.4.3:compile
[INFO] |  +- org.springframework.retry:spring-retry:jar:1.3.1:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-function-context:jar:3.1.0:compile
[INFO] |     +- net.jodah:typetools:jar:0.6.2:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-function-core:jar:3.1.0:compile
```

**The failing test is green now. Seems to be fixed somehow.**


I had a ClassCastException at the beginning but I think that you have to convert your object to a Message befor you return it? Is this the expected behaviour? Exception happened here: `org.springframework.cloud.stream.function.FunctionConfiguration#589`

I'm during the imparativ to functional approach migration and with the imperative approach you were able to just return the object instead of converting it to a message by ourself.

This works now if the object is converted to a message:
```
  @Nullable
  public Message<R> handleIncomingMessage(Message<T> eventMessage) {
      T event = eventMessage.getPayload();
      ...
      R result = handleEvent(event, topic, partitionId, consumer, acknowledgment);
      return result != null ? MessageBuilder.withPayload(result).build() : null; //<--- convert if not null
  }
```


This implementation leads to the ClassCastException:
```
@Nullable
public R handleIncomingMessage(Message<T> eventMessage) {
  T event = eventMessage.getPayload();
  ...
  return handleEvent(event, topic, partitionId, consumer, acknowledgment);
}
```

**Comment by olegz** [comment]
Ok, can you please include the stack trace?

**Comment by Chr3is** [comment]
Ofc - I've removed some sensetive data

```
2021-02-09 19:36:48.055 ERROR 2040 --- [container-0-C-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@33d8b388]; nested exception is java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app'), failedMessage=GenericMessage [payload={***}), kafka_groupId=***, target-protocol=kafka}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:396)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:78)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:455)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:429)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2065)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2047)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1984)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1924)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1812)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1531)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1178)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1075)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app')
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:589)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:575)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 26 more

2021-02-09 19:36:48.084 ERROR 2040 --- [container-0-C-1] o.s.k.l.SeekToCurrentErrorHandler        : Backoff none exhausted for ConsumerRecord(***)

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@33d8b388]; nested exception is java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app'), failedMessage=GenericMessage [payload={***}]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2113)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:2098)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1997)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1924)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1812)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1531)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1178)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1075)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@33d8b388]; nested exception is java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app')
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:396)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:78)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:455)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:429)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2065)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2047)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1984)
	... 8 common frames omitted
Caused by: java.lang.ClassCastException: class ...MyEvent cannot be cast to class org.springframework.messaging.Message (...MyEvent and org.springframework.messaging.Message are in unnamed module of loader 'app')
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:589)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:575)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 26 common frames omitted
```

Gary Russell gave me the example
```
@Bean
Function<Message< MyIncomingEvent>, MyOutgoingEvent>() {
    return eventMsg -> ...
}

so maybe he did a little mistake and Message<MyOutgoingEvent> is required or the behaviour with the ClassCastException is not intended. 
```

**Comment by olegz** [comment]
Unfortunately I still can't reproduce it. In fact there is already a [test case](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/ScenarioTests.java#L61) for this specific issue and new code associated with the fix. 

So, I am resolving this one. If you believe there is still an issue, please submit a failing test or small project that reproduces the issue so we can investigate

**Comment by matus753** [comment]
Hi, 

I am sending small project to reproduce NullPointer we are encoutering. Just run test in DummyMapperTest.java.

[dummy-app.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5958778/dummy-app.zip)

**Comment by olegz** [comment]
I've ran it against current master and it passes just fine. Here is the updated POM from your app
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.2</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>dummy-app</artifactId>
    <version>1.0.0.BUILD-SNAPSHOT</version>

    <properties>
        <java.version>11</java.version>
        <spring-cloud.version>2020.0.1</spring-cloud.version>
        <spring-cloud-stream.version>3.1.0</spring-cloud-stream.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-stream-dependencies</artifactId>
                <version>${spring-cloud-stream.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
             <version>3.1.2-SNAPSHOT</version>
        </dependency>


        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.dummy.app.DummyAppApplication</mainClass>
                    <finalName>dummy-app</finalName>
                    <skip>false</skip>
                    <addResources>true</addResources>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

```

If you have troubles getting the right snapshot in simply clone the project

```
git clone git@github.com:spring-cloud/spring-cloud-stream.git
cd spring-cloud-stream
./mvnw clean install -DskipTests
```

**Comment by carlsylvia** [comment]
I am still experiencing the issue reported by @matus753.  I have the same usecase of needing to handle cases where a Function may return null and have output skipped, however it always attempts to send to output and a NPE is thrown.  I have downloaded and installed the current 3.1.2-SNAPSHOT, and it still fails in my codebase.  I downloaded the sample project that @matus753 provided, and updated the POM per the feedback from @olegz, and the tests in that dummy project fail with the following trace:

```
Caused by: java.lang.NullPointerException: null
	at org.springframework.messaging.core.GenericMessagingTemplate.sendTimeout(GenericMessagingTemplate.java:252) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.messaging.core.AbstractDestinationResolvingMessagingTemplate.send(AbstractDestinationResolvingMessagingTemplate.java:72) ~[spring-messaging-5.3.3.jar:5.3.3]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:585) ~[spring-cloud-stream-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:571) ~[spring-cloud-stream-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56) ~[spring-integration-core-5.4.3.jar:5.4.3]
```

**Comment by olegz** [comment]
@carlsylvia Are you sure you used the current master? Did you build it locally (we may have issue with publishing snapshots so you may not get the latest, we are working on resolving it)?

**Comment by olegz** [comment]
@carlsylvia  No, you are correct, then I guess I need a way to reproduce it as I am clearly missing something. I've tested it against the app provided by @matus753 earlier in this thread and it works.

**Comment by carlsylvia** [comment]
@olegz I just blew-away my local maven repo and am doing a full rebuild.  I'll let you know if that resolves anything.

**Comment by carlsylvia** [comment]
@olegz I rebuilt the most current version of master, which also required I build a local snapshot of spring-cloud-function.  I updated my build.gradle to require these new versions.  This version WORKS!!!  I tested with both function.definition and function.routing-expression and each are behaving as expected when null is returned by the function.  

When will these versions be released and available via Maven Central?


    implementation('org.springframework.cloud:spring-cloud-stream') {
        version {
            strictly '3.1.2-SNAPSHOT'
        }
    }
    implementation('org.springframework.cloud:spring-cloud-starter-function-web') {
        version {
            strictly '3.1.2-SNAPSHOT'
        }
    }

**Comment by andrewchouman** [comment]
I'm facing the same issue in v3.1.3. See my [Stack Overflow](https://stackoverflow.com/questions/67961934/nullpointerexception-when-supplier-returns-null-in-spring-cloud-stream-3-x) post. Is this still an ongoing bug?

Here is my full pom for reproduction purposes:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.1</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>logging-consumer</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>logging-consumer</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>2020.0.3</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
			<version>3.1.3</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
			<scope>test</scope>
			<classifier>test-binder</classifier>
			<type>test-jar</type>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
			<scope>test</scope>
		</dependency>
		
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
`
