### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-stream#2975]
On https://spring.io/projects/spring-cloud-stream#learn there are two broken links:

* 4.1.3 links to https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/, which shows the documentation for version 4.0.5.
* 4.1.4-SNAPSHOT links to https://docs.spring.io/spring-cloud-stream/docs/4.1.4-SNAPSHOT/reference/html/, which returns 404 Not Found.

It looks like the correct URL format is https://docs.spring.io/spring-cloud-stream/reference/${version}, because these work:

* 4.1.3: https://docs.spring.io/spring-cloud-stream/reference/4.1.3
* 4.1.4-SNAPSHOT: https://docs.spring.io/spring-cloud-stream/reference/4.1.4-SNAPSHOT

**Comment by olegz** [comment]
Fixed for both stream and function 

https://spring.io/projects/spring-cloud-stream#learn
https://spring.io/projects/spring-cloud-function#learn

**Comment by breun** [comment]
On https://spring.io/projects/spring-cloud-stream#learn the link for 4.1.3 still points to https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/, which displays the documentation for version 4.0.5. I think 4.1.3 should point to https://docs.spring.io/spring-cloud-stream/reference/4.1.3

And a similar issue still exists for https://spring.io/projects/spring-cloud-function#learn

**Comment by olegz** [comment]
we're looking into that, it is actually a problem across many cloud projects

**Comment by olegz** [comment]
fixed

**Comment by breun** [comment]
> we're looking into that, it is actually a problem across many cloud projects

Yeah, I noticed that too, so I opened a lot of tickets about this. :)
