### ISSUE TITLE
unable to set kafka consumer group and startOffset in spring cloud stream kafka

### ISSUE THREAD

**Issue by charan1595** [spring-cloud/spring-cloud-stream#995]
https://stackoverflow.com/questions/44677210/unable-to-set-kafka-properties-in-spring-cloud-stream-kafka

**Comment by ilayaperumalg** [comment]
@charan1595 I think this is fixed here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/7355ada4613ad50fe95430f1859d4ea65f004be1

Also, it is recommended to open the issue in the appropriate binder (in this case here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka)

**Comment by chintanshah24** [comment]
@ilayaperumalg How do we use this commit through maven?

**Comment by sobychacko** [comment]
@chintanshah24 the latest build snapshots have this change: http://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-stream-binder-kafka/1.3.0.BUILD-SNAPSHOT/

**Comment by charan1595** [comment]
it still doesnt work, my pom.xml is 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.media.cm</groupId>
    <artifactId>Arbitrage-Adclick-Consumer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.7</java.version>
        <junit.version>4.11</junit.version>
    </properties>
    
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.*</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                    <maxmem>1024m</maxmem>
                    <fork>true</fork>
                </configuration>
            </plugin>
            
            <plugin>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <configuration>
                        <descriptorRefs>
                            <descriptorRef>jar-with-dependencies</descriptorRef>
                        </descriptorRefs>
                        <archive>
                            <manifest>
                                <mainClass>net.media.cm.kafka.examples.ArbitrageAdclickConsumer</mainClass>
                            </manifest>
                        </archive>
                    </configuration>
                    <executions>
                        <execution>
                            <id>make-assembly</id>
                            <phase>package</phase>
                            <goals>
                                <goal>single</goal>
                            </goals>
                        </execution>
                    </executions>
            </plugin>
            
        </plugins>
    </build>
    
    <dependencies>
        <dependency>
            <groupId>net.media.cm</groupId>
            <artifactId>logging-kafka</artifactId>
            <version>1.0.6</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.jtds</groupId>
            <artifactId>jtds</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.4.2</version>
           <!-- <scope>provided</scope>-->
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
          <!--  <scope>provided</scope>-->
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <version>1.4</version>
        </dependency>
    </dependencies>
    
</project>
```


and my application.properties file is 


```
#spring.cloud.stream.bindings.output.content-type=application/json
#spring.cloud.stream.bindings.input.contentType=application/json
spring.cloud.stream.bindings.output.contentType=application/x-java-object;type=com.example.demo.KafkaApplication.Message
eureka.client.service-url.default-zone=http://172.16.165.26:8761/eureka/
spring.cloud.stream.kafka.binder.zkNodes=10.6.22.20
#spring,cloud.stream.kafka.binder.brokers=10.6.22.20
spring.kafka.bootstrap-servers=10.6.22.20:9092
#spring.kafka.consumer.group-id=example-consumer-1
spring.cloud.stream.instanceCount=1
spring.cloud.stream.instanceIndex=0
spring.kafka.consumer.auto-offset-reset=latest
spring.cloud.stream.kafka.bindings.output.group=example-consumer-1
spring.cloud.stream.kafka.bindings.output.consumer.instanceCount=1
spring.cloud.stream.kafka.bindings.output.consumer.instanceIndex=0
spring.cloud.stream.kafka.bindings.output.consumer.resetOffsets=true
spring.cloud.stream.kafka.bindings.output.consumer.startOffset=earliest
```


i can see from the logs that the group is anonymous group, its not taking the group to the topic 'output' set in the application.properties which is example-consumer-1

**Comment by mbogoevici** [comment]
@charan1595 The property is commented out in the example you posted.

**Comment by mbogoevici** [comment]
@charan1595 The property you're expecting to set is commented out: 

```
#spring.kafka.consumer.group-id=example-consumer-1
```

Or you're setting consumer properties on an output channel (which can't possibly work).

**Comment by charan1595** [comment]
i commented that out on purpose. i want use a specific group to consume on a specific topic,like i want to consume using example-consumer-1 group on topic 'output'.

**Comment by olegz** [comment]
@charan1595 this issue appears to stall and since June 2017 there were many changes, so I will close it for now, but please feel free to re-open or raise the new one if you still have questions

**Comment by marcuslinke** [comment]
@olegz I ran into the same issue with latest spring boot (2.1.3-RELEASE) and kafka streams binder "spring-cloud-stream-binder-kafka-streams-2.1.2.RELEASE.jar". It's still not possible to set a special consumer group like this:

```yml
spring:
  cloud:
    stream:
      bindings:
        inputChannel:
          destination: topic
          group: specialGroup
```
With this application.yml in place the special consumer group is silently ignored.

**Comment by nedijahij** [comment]
> @olegz I ran into the same issue with latest spring boot (2.1.3-RELEASE) and kafka streams binder "spring-cloud-stream-binder-kafka-streams-2.1.2.RELEASE.jar". It's still not possible to set a special consumer group like this:
> 
> ```yaml
> spring:
>   cloud:
>     stream:
>       bindings:
>         inputChannel:
>           destination: topic
>           group: specialGroup
> ```
> 
> With this application.yml in place the special consumer group is silently ignored.

Any solutions found yet?

**Comment by jeeftor** [comment]
We're still seeing the same issue as well

**Comment by olegz** [comment]
@jeeftor this is a closed and outdated issue. Aside from the fact that it is closed and should not be commented on it is hard for someone to grasp the context. 

Please raise new issue, provide enough information on how to reproduce, specify exact versions of frameworks used and link to this issue if you wish
